using System.Diagnostics;
using System.IO;
using System.Text.Json;
using System.Windows;
using System.Windows.Controls;
using System.Windows.Input;
using System.Windows.Media;
using System.Windows.Media.Imaging;
using System.Windows.Threading;
using X20Ctl.Zone;
namespace X20Ctl.Product.Development;
internal static class ManagementReview
{
    private static IEnumerable<DependencyObject> Descendants(DependencyObject root){for(int i=0;i<VisualTreeHelper.GetChildrenCount(root);i++){var child=VisualTreeHelper.GetChild(root,i);yield return child;foreach(var nested in Descendants(child))yield return nested;}}
    public static async Task Run(string directory)
    {
        Directory.CreateDirectory(directory);var checks=new List<object>();var shots=new List<object>();var log=new StringWriter();using var listener=new TextWriterTraceListener(log);PresentationTraceSources.DataBindingSource.Listeners.Add(listener);PresentationTraceSources.DataBindingSource.Switch.Level=SourceLevels.Error;
        void Check(bool pass,string name){checks.Add(new{name,passed=pass});if(!pass)throw new InvalidOperationException(name);}
        var window=new ProductWindow(false,Path.Combine(directory,"assignments-fixture.json"));
        try
        {
            window.Show();await Ready();window.Scene.AssignController(0,window.Host.Catalog.Get("x20"));window.Host.EnterStudio(0);var scene=window.Host.Studio!;scene.ShowManagement("Device");await Capture("device-maximized.png");
            Check(scene.Device!.State.GameplayStatus=="Offline" && scene.Device.State.ConfigurationStatus=="Offline" && scene.Device.State.Firmware==null && !scene.Apply.IsEnabled,"Device keeps assigned model separate from unavailable connections and telemetry");SendKey(Key.F6);scene.Device.OpenTester.Focus();await Capture("device-focus.png");
            scene.Device.OpenTester.RaiseEvent(new RoutedEventArgs(Button.ClickEvent));await Capture("tester-offline-maximized.png");Check(scene.InputContext==InputOwner.TesterCapture && scene.Tester!.State.OwnsInput,"Tester owns gameplay input context");
            var frame=new TesterFrame("x20","Review fixture · no hardware",true,1,["A","DPAD_UP","L3","M1"],["A","DPAD_UP","L3"],.55,-.35,-.3,.4,.75,.2);
            Check(scene.DeliverGameplayFrame(frame),"typed labelled review fixture reaches Tester");SendKey(Key.A);SendKey(Key.B);Check(scene.ManagementPage=="Tester" && !scene.Tester!.State.CanNavigateGameplay,"gameplay test buttons cannot navigate the UI");await Capture("tester-fixture-front.png");Check(scene.Tester!.IsIlluminated("A") && scene.Tester.IsIlluminated("DPAD_UP"),"shared owned A and Up regions respond to fixture");scene.Tester.ShowRear(true);await Capture("tester-fixture-rear.png");Check(scene.Tester.IsIlluminated("LT") && !scene.Tester.IsIlluminated("M1"),"owned trigger responds without inventing independent M1 input");
            scene.Tester.Exit.RaiseEvent(new RoutedEventArgs(Button.ClickEvent));Check(scene.ManagementPage=="Device" && !scene.Tester.State.OwnsInput && scene.Tester.State.Frame==null,"deliberate exit releases capture and clears stale input");
            scene.ShowManagement("Setups");var setups=scene.Setups!;await Capture("setups-empty-maximized.png");scene.Draft.Set("A","B");scene.Curves.Draft.SetPreset(CurveChannel.LeftStick,"quick");scene.Curves.Draft.SetPreset(CurveChannel.RightStick,"fine");setups.SaveButton.RaiseEvent(new RoutedEventArgs(Button.ClickEvent));string original=setups.SelectedId!;setups.RenameButton.RaiseEvent(new RoutedEventArgs(Button.ClickEvent));setups.NameField.Text="Precision layout";setups.SaveNameButton.RaiseEvent(new RoutedEventArgs(Button.ClickEvent));setups.DuplicateSelected();setups.RenameButton.RaiseEvent(new RoutedEventArgs(Button.ClickEvent));setups.NameField.Text="Daily play";setups.SaveNameButton.RaiseEvent(new RoutedEventArgs(Button.ClickEvent));await Capture("setups-library-maximized.png");
            Check(Descendants(setups.Body).OfType<Button>().Where(b=>b.Content is StackPanel && b.ActualHeight>100).All(b=>b.ActualWidth>=350 && b.ActualHeight>=260),"library cards retain console scale");Check(setups.Store.Items.Count==2 && setups.Store.Items.Any(s=>s.Name=="Precision layout"),"local setup save rename and duplication implemented");setups.Select(original);setups.OpenButton.RaiseEvent(new RoutedEventArgs(Button.ClickEvent));Check(setups.ActiveId==original && scene.Draft.Target("A")=="B" && !scene.Apply.IsEnabled,"opening setup changes the local editor only");await Capture("setups-selected-detail.png");Check(setups.SetupCards.Count==2 && setups.DetailWorkspace.IsVisible && setups.DetailWorkspace.TransformToAncestor(setups.Body).Transform(new Point()).Y<setups.Body.ActualHeight-180,"selected setup has integrated visible details");scene.Draft.Set("X","Y");setups.RefreshCurrent();Check(setups.Notice.Contains("local changes"),"active setup modified state is distinct from saved copy");await Capture("setups-modified.png");
            string copy=setups.Store.Items.Single(s=>s.Id!=original).Id;setups.Select(copy);setups.MoreButton.RaiseEvent(new RoutedEventArgs(Button.ClickEvent));Check(setups.MoreButton.ContextMenu!.IsOpen,"destructive action is available through secondary menu");setups.DeleteAction.RaiseEvent(new RoutedEventArgs(MenuItem.ClickEvent));await Capture("setups-delete-confirmation.png");Check(setups.DeletePending && setups.Store.Items.Count==2,"delete requires explicit confirmation");SendKey(Key.Y);Check(setups.Store.Items.Count==2 && setups.DeletePending,"confirmation traps unrelated navigation actions");SendKey(Key.Escape);Check(setups.Store.Items.Count==2,"cancel preserves setup");setups.RequestDelete(copy);SendKey(Key.Tab);SendKey(Key.Enter);Check(setups.Store.Items.Count==1,"confirmed delete removes only native library entry");await Capture("setups-one-maximized.png");
            string export=Path.Combine(directory,"exported-native-setup.json");setups.Select(original);setups.ExportPath(export);setups.ImportPath(export);Check(setups.Store.Items.Count==1,"native import/export is idempotent for identical identity");
            string legacy=Path.Combine(directory,"legacy-profiles-fixture.json");byte[] legacyBytes=System.Text.Encoding.UTF8.GetBytes("[{\"id\":\"legacy-1\",\"name\":\"Preserved legacy setup\",\"controllerId\":\"x20\",\"vibration\":60,\"unknownField\":{\"keep\":true}}]");File.WriteAllBytes(legacy,legacyBytes);setups.ImportPath(legacy);setups.ImportPath(legacy);await Capture("setups-legacy-preserved.png");Check(setups.Store.Items.Count==2 && legacyBytes.SequenceEqual(File.ReadAllBytes(legacy)) && !setups.OpenButton.IsEnabled,"legacy copy retains original bytes and forbids unverified semantic loading");
            Check(Directory.GetFiles(Path.Combine(Path.GetDirectoryName(setups.Store.PathName)!,"legacy-backups")).Length>=2,"legacy exact-byte backup and manifest exist");setups.ExportPath(Path.Combine(directory,"exported-legacy-copy.json"));Check(File.ReadAllText(Path.Combine(directory,"exported-legacy-copy.json")).Contains("unknownField"),"legacy export retains unknown fields");
            foreach(string page in new[]{"Device","Tester","Setups"})
            {
                scene.ShowManagement(page);window.WindowState=WindowState.Normal;window.Width=1220;window.Height=800;await Capture(page.ToLowerInvariant()+"-restored.png");window.Width=1040;window.Height=700;await Capture(page.ToLowerInvariant()+"-minimum.png");Check(scene.Apply.ActualWidth>=155 && !scene.Apply.IsEnabled,page+" minimum retains unavailable Apply");window.WindowState=WindowState.Maximized;await Capture(page.ToLowerInvariant()+"-maximized-final.png");
            }
            scene.ShowManagement("Setups");if(scene.StatusNote.Text!="Navigation preview")SendKey(Key.F6);setups.NewButton.Focus();await Capture("setups-focus.png");string? selectedBeforeFocus=setups.SelectedId;setups.SetupCards.First().Focus();await Capture("setups-card-focus.png");Check(Keyboard.FocusedElement==setups.SetupCards.First() && setups.SelectedId==selectedBeforeFocus,"card focus is distinct from selection");window.Host.ReturnToZone();window.Host.EnterStudio(0);scene=window.Host.Studio!;scene.ShowManagement("Setups");Check(scene.Setups!.Store.Items.Count==2 && scene.Setups.ActiveId==original,"native library and per-player editor assignment survive Studio re-entry");
            var motionFrames=new List<BitmapFrame>();
            foreach(string page in new[]{"Device","Tester","Setups"})
            {
                scene.ShowManagement(page);
                if(page=="Tester")scene.DeliverGameplayFrame(frame);
                for(int i=0;i<12;i++){await Task.Delay(40);window.UpdateLayout();var bitmap=new RenderTargetBitmap((int)Math.Ceiling(window.Host.ActualWidth*.7),(int)Math.Ceiling(window.Host.ActualHeight*.7),67.2,67.2,PixelFormats.Pbgra32);bitmap.Render(window.Host);motionFrames.Add(BitmapFrame.Create(bitmap));}
            }
            var motion=new GifBitmapEncoder();foreach(var bitmap in motionFrames)motion.Frames.Add(bitmap);string motionPath=Path.Combine(directory,"management-transitions-simulation.gif");using(var stream=File.Create(motionPath))motion.Save(stream);StudioReview.SetGifDelays(motionPath,4);
            Check(motionFrames.Count==36,"management page transition sequence recorded with labelled simulation");
            window.Host.ReturnToZone();window.Scene.AssignController(1,window.Host.Catalog.Get("x15"));window.Host.EnterStudio(1);scene=window.Host.Studio!;scene.ShowManagement("Device");await Capture("device-x15-reference.png");scene.ShowManagement("Setups");Check(!scene.Setups!.NewButton.IsEnabled && !scene.Apply.IsEnabled,"research model cannot gain X20 native setup editing or hardware writes");scene.Setups.Select(original);Check(!scene.Setups.OpenButton.IsEnabled,"incompatible setup cannot open in this model editor");await Capture("setups-incompatible-maximized.png");
            var reduced=new ProductWindow(true,Path.Combine(directory,"reduced-fixture.json"));try{reduced.Show();await Task.Delay(300);reduced.Scene.AssignController(0,reduced.Host.Catalog.Get("x20"));reduced.Host.EnterStudio(0);foreach(string page in new[]{"Device","Tester","Setups"}){reduced.Host.Studio!.ShowManagement(page);await Task.Delay(250);reduced.UpdateLayout();Save(reduced.Host,page.ToLowerInvariant()+"-reduced-motion.png",1);}Check(!reduced.Host.Studio!.AnimationsEnabled,"all management pages respect reduced motion");}finally{reduced.Close();}
            foreach(double scale in new[]{1d,1.25,1.5})foreach(string page in new[]{"Device","Tester","Setups"}){double width=1920/scale,height=1040/scale;var dpiStore=new SetupStore(Path.Combine(directory,"dpi-"+page+"-"+scale+".json"));dpiStore.Load();if(page=="Setups")for(int i=0;i<5;i++)dpiStore.Create("DPI profile "+(i+1),SetupSnapshot.Capture("x20",new("x20"),new("x20"),new("x20"),new("x20")));var root=new StudioScene(0,window.Host.Catalog.Get("x20"),new("x20"),true,setups:dpiStore){Width=width,Height=height};root.ShowManagement(page);VisualTreeHelper.SetRootDpi(root,new(scale,scale));root.Measure(new(width,height));root.Arrange(new(0,0,width,height));root.UpdateLayout();await window.Dispatcher.InvokeAsync(()=>{},DispatcherPriority.ContextIdle);root.UpdateLayout();Save(root,$"render-dpi-{scale*100:0}-{page.ToLowerInvariant()}.png",scale);}
            window.Host.ReturnToZone();window.Host.EnterStudio(0);scene=window.Host.Studio!;scene.ShowManagement("Setups");
            var names=new[]{"FPS · Quick response","Racing · Smooth steering","Evening co-op","Platformer","Fine aim","Default controls","Arcade","Precision alternate","Long session","Trigger control","Daily play alternate","Travel setup"};
            string? last=null;foreach(string title in names){var snapshot=SetupSnapshot.Capture("x20",new("x20"),new("x20"),new("x20"),new("x20"));last=scene.Setups!.Store.Create(title,snapshot).Id;}
            window.Host.ReturnToZone();window.Host.EnterStudio(0);scene=window.Host.Studio!;scene.ShowManagement("Setups");var many=scene.Setups!;many.Select(original);await Capture("setups-many-maximized.png");
            Check(many.SetupCards.Count==14 && many.SetupCards.All(b=>b.ActualWidth>=350 && b.ActualHeight>=260),"many setups wrap without shrinking cards");Check(many.SetupCards.Take(4).Select(b=>b.TransformToAncestor(many.Body).Transform(new Point()).Y).Distinct().Count()==1,"maximized library fits four complete cards per row");
            many.Select(last!);await Capture("setups-many-last-selected.png");Check(many.LibraryViewport.VerticalOffset>0,"last setup scrolls into library viewport");
            window.WindowState=WindowState.Normal;window.Width=1040;window.Height=700;await Ready();many.OpenButton.Focus();many.OpenButton.BringIntoView();await Capture("setups-many-minimum-detail.png");Check(many.SetupCards.All(b=>b.ActualWidth>=350 && b.ActualHeight>=260),"minimum library retains readable cards with scrolling");window.WindowState=WindowState.Maximized;
            scene.ShowCurves(false);await Capture("buttons-after-library.png");Check(scene.ManagementPage==null && Grid.GetRowSpan(scene.StudioBody)==1 && !scene.Apply.IsEnabled,"leaving library restores approved Buttons layout and unavailable Apply");
            scene.ShowCurves(true);await Capture("curves-after-library.png");Check(Grid.GetRowSpan(scene.StudioBody)==1 && scene.IsCurves,"Curves remains in approved body/shelf layout");
            scene.ShowMacros(true);await Capture("macros-after-library.png");Check(Grid.GetRowSpan(scene.StudioBody)==1 && scene.IsMacros,"Macros remains in approved body/shelf layout");
            scene.ShowVibration(true);await Capture("vibration-after-library.png");Check(Grid.GetRowSpan(scene.StudioBody)==1 && scene.IsVibration,"Vibration remains in approved body/shelf layout");
            listener.Flush();Check(log.ToString().Length==0,"no WPF binding errors");File.WriteAllText(Path.Combine(directory,"bindings.txt"),log.ToString());File.WriteAllText(Path.Combine(directory,"review.json"),JsonSerializer.Serialize(new{status="passed",hardwareAccess=false,desktopInputInjected=false,testerData="explicit review fixtures only; actual native input bridge not connected",captureKind="shown WPF client renders plus labelled root-DPI matrix",checks,shots,setupStore=setups.Store.PathName,legacyFixturePreserved=legacyBytes.SequenceEqual(File.ReadAllBytes(legacy))},new JsonSerializerOptions{WriteIndented=true}));
        }
        finally{window.Close();PresentationTraceSources.DataBindingSource.Listeners.Remove(listener);}
        void SendKey(Key key){window.Host.Studio!.OnKeyDown(window,new KeyEventArgs(Keyboard.PrimaryDevice,PresentationSource.FromVisual(window)!,0,key){RoutedEvent=Keyboard.PreviewKeyDownEvent});}
        async Task Ready(){await window.Dispatcher.InvokeAsync(()=>{},DispatcherPriority.ContextIdle);await Task.Delay(300);window.UpdateLayout();}
        async Task Capture(string file){await Ready();Save(window.Host,file,1);}
        void Save(FrameworkElement root,string file,double scale){var image=new RenderTargetBitmap((int)Math.Ceiling(root.ActualWidth*scale),(int)Math.Ceiling(root.ActualHeight*scale),96*scale,96*scale,PixelFormats.Pbgra32);image.Render(root);var encoder=new PngBitmapEncoder();encoder.Frames.Add(BitmapFrame.Create(image));using(var stream=File.Create(Path.Combine(directory,file)))encoder.Save(stream);shots.Add(new{file,width=image.PixelWidth,height=image.PixelHeight});}
    }
}
