#include "x20_codec.hpp"
#include <cmath>
#include <stdexcept>
namespace x20ctl {
static constexpr std::array<std::uint8_t,15> data_key{51,99,157,121,242,219,162,26,170,33,139,232,116,211,88};
static constexpr std::array<std::uint8_t,40> serial_key{161,82,213,163,245,137,246,143,240,157,72,147,234,52,49,186,195,77,198,235,73,96,216,163,218,42,83,141,244,97,24,191,174,215,111,81,228,160,217,146};
static void packet_size(std::size_t size){if(size<5||size>20)throw std::invalid_argument("packet must contain 5–20 bytes");}
std::uint8_t crc8(std::span<const std::uint8_t> bytes){std::uint8_t crc=0;for(auto value:bytes){crc^=value;for(int bit=0;bit<8;++bit)crc=static_cast<std::uint8_t>((crc>>1)^((crc&1)?0xeb:0));}return crc;}
Bytes scramble(std::span<const std::uint8_t> bytes){packet_size(bytes.size());Bytes out(bytes.begin(),bytes.end());int b2=bytes[2],b3=bytes[3];out[0]=static_cast<std::uint8_t>(bytes[0]^((b2+b3)-154));out[1]=static_cast<std::uint8_t>(bytes[1]^((b2+b3)+155));out[2]=static_cast<std::uint8_t>((b2-173)^b3);out[3]=static_cast<std::uint8_t>((b3+191)^219);for(std::size_t i=4;i+1<bytes.size();++i)out[i]=static_cast<std::uint8_t>(bytes[i]^((b2+b3)-data_key[i-4]));std::size_t offset=(out[3]&2)*10;for(std::size_t i=0;i<out.size();++i)out[i]^=serial_key[offset+i];return out;}
Bytes unscramble(std::span<const std::uint8_t> bytes){packet_size(bytes.size());Bytes out(bytes.begin(),bytes.end());std::size_t offset=((bytes[3]^serial_key[3])&2)?20:0;for(std::size_t i=0;i<out.size();++i)out[i]^=serial_key[offset+i];int b3=static_cast<std::uint8_t>((out[3]^219)-191);out[3]=static_cast<std::uint8_t>(b3);int b2=static_cast<std::uint8_t>((out[2]^b3)+173);out[2]=static_cast<std::uint8_t>(b2);out[1]=static_cast<std::uint8_t>(out[1]^((b2+b3)+155));out[0]=static_cast<std::uint8_t>(out[0]^((b2+b3)-154));for(std::size_t i=4;i+1<out.size();++i)out[i]=static_cast<std::uint8_t>(out[i]^((b2+b3)-data_key[i-4]));return out;}
Bytes frame(std::uint8_t op,std::uint8_t length,std::uint8_t serial,std::uint8_t nonce,std::span<const std::uint8_t> payload){packet_size(payload.size()+5);Bytes data{op,length,serial,nonce};data.insert(data.end(),payload.begin(),payload.end());data.push_back(crc8(data));return scramble(data);}
Packet decode(std::span<const std::uint8_t> bytes){auto data=unscramble(bytes);return {data[0],data[1],data[2],data[3],Bytes(data.begin()+4,data.end()-1),crc8(std::span(data).first(data.size()-1))==data.back()};}
std::uint8_t save_serial(int slot,int counter){if(slot<0||slot>15||counter<0)throw std::invalid_argument("invalid slot/counter");return static_cast<std::uint8_t>(((counter%2)<<7)|(slot<<3)|(counter%8));}
std::uint8_t host_length(int size,int counter){if(size<0||counter<0)throw std::invalid_argument("invalid length/counter");return size==0?5:static_cast<std::uint8_t>(((counter%8)<<5)|((size+5)&31));}
Bytes macro_payload(std::span<const MacroEntry> entries,int loop_ms,int trigger){if(entries.size()>47||loop_ms<0||loop_ms%5||loop_ms/5>=4096||trigger<0||trigger>1)throw std::invalid_argument("invalid macro capacity/header");int ticks=loop_ms/5;Bytes result{static_cast<std::uint8_t>(entries.size()*5+2),static_cast<std::uint8_t>(ticks&255),static_cast<std::uint8_t>((trigger<<7)|((ticks>>8)&15))};for(auto step:entries){if(step.mask>=1u<<24||step.duration_ms<0||step.duration_ms%5||step.duration_ms/5>65535)throw std::invalid_argument("invalid macro step");int duration=step.duration_ms/5;result.push_back(static_cast<std::uint8_t>(step.mask));result.push_back(static_cast<std::uint8_t>(step.mask>>8));result.push_back(static_cast<std::uint8_t>(step.mask>>16));result.push_back(static_cast<std::uint8_t>(duration));result.push_back(static_cast<std::uint8_t>(duration>>8));}return result;}
Bytes mapping(std::span<const std::uint8_t> sources,std::span<const std::uint8_t> targets){if(sources.size()!=targets.size()||sources.size()>255)throw std::invalid_argument("mapping source/target mismatch");Bytes result{static_cast<std::uint8_t>(sources.size())};for(std::size_t i=0;i<sources.size();++i)result.push_back(sources[i]==targets[i]?0:targets[i]);return result;}
Bytes vibration(int percent,std::span<const std::uint8_t> body){if(percent<0||percent>100||body.size()<3)throw std::invalid_argument("vibration requires current record");double raw=percent*255.0/100.0;int low=static_cast<int>(std::floor(raw));int value=raw-low>.5?low+1:raw-low<.5?low:low+(low%2);Bytes result(body.begin(),body.end());result[1]=result[2]=static_cast<std::uint8_t>(value);return result;}
Bytes curve(std::span<const std::uint8_t> raw){if(raw.size()!=7)throw std::invalid_argument("curve record must be 7 bytes");return Bytes(raw.begin(),raw.end());}
double normalize_axis(int raw){if(raw<-32768||raw>32767)throw std::invalid_argument("axis outside signed 16-bit range");return raw<0?raw/32768.0:raw/32767.0;}
Bytes from_hex(const std::string& text){if(text=="-"||text.empty())return {};if(text.size()%2)throw std::invalid_argument("odd hex");Bytes result;for(std::size_t i=0;i<text.size();i+=2){std::size_t consumed=0;auto value=std::stoul(text.substr(i,2),&consumed,16);if(consumed!=2)throw std::invalid_argument("invalid hex");result.push_back(static_cast<std::uint8_t>(value));}return result;}
std::string hex(std::span<const std::uint8_t> bytes){static constexpr char digits[]="0123456789abcdef";std::string result;for(auto byte:bytes){result+=digits[byte>>4];result+=digits[byte&15];}return result;}
bool authorize_write(const std::string&,const std::string&){return false;}
}
